#!/usr/bin/env bash

echo "Seed MongoDB database"

SEED_DIR=${SEED_DIR:-$(cd $(dirname $0); pwd)}
DATABASE_CONNECTION_STRING=${DATABASE_CONNECTION_STRING:-mongodb://localhost:27017/vimcolorschemes}

mongoimport \
  --uri $DATABASE_CONNECTION_STRING \
  --db vimcolorschemes \
  --collection repositories \
  --jsonArray \
  --drop \
  --file ${SEED_DIR}/seed.json

echo "Done seeding"
