name: Code quality check

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  quality:
    name: Check types, lint, and format
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set up pnpm
        uses: pnpm/action-setup@v4

      - name: Set up Node.js
        uses: actions/setup-node@v5
        with:
          node-version-file: .nvmrc
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Type check
        run: pnpm tsc --noEmit

      - name: Test
        run: pnpm test

      - name: Lint check
        run: pnpm lint.check

      - name: Format check
        run: pnpm format.check
