name: e2e tests

on:
  push:
    branches: [ main ]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: cypress-io/github-action@v2
        with:
          record: true
          browser: chrome
          headless: true
          build: npm run build.ci
          start: npm run serve
          wait-on: http://localhost:9000
          config: baseUrl=http://localhost:9000
        env:
          GATSBY_DATABASE_CONNECTION_STRING: ${{ secrets.GATSBY_DATABASE_CONNECTION_STRING }}
          GATSBY_SITE_URL: https://localhost:9000
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
