name: Run tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  unit_tests:
    name: Run unit tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: npm ci
    - name: Run unit tests
      run: npm run test
  e2e_tests:
    name: Run E2E tests on Chrome
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: cypress-io/github-action@v2
        with:
          record: true
          browser: chrome
          headless: true
          build: npm run build.preview
          start: npm run serve
          wait-on: http://localhost:9000
          config: baseUrl=http://localhost:9000
        env:
          GATSBY_DATABASE_CONNECTION_STRING: ${{ secrets.GATSBY_DATABASE_CONNECTION_STRING }}
          GATSBY_SITE_URL: https://localhost:9000
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
